<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| File and Directory Modes
|--------------------------------------------------------------------------
|
| These prefs are used when checking and setting modes when working
| with the file system.  The defaults are fine on servers with proper
| security, but you may wish (or even need) to change the values in
| certain environments (Apache running a separate process for each
| user, PHP under CGI with Apache suEXEC, etc.).  Octal values should
| always be used to set the mode correctly.
|
*/
define('FILE_READ_MODE', 0644);
define('FILE_WRITE_MODE', 0666);
define('DIR_READ_MODE', 0755);
define('DIR_WRITE_MODE', 0755);

/*
|--------------------------------------------------------------------------
| File Stream Modes
|--------------------------------------------------------------------------
|
| These modes are used when working with fopen()/popen()
|
*/
define('FOPEN_READ', 'rb');
define('FOPEN_READ_WRITE', 'r+b');
define('FOPEN_WRITE_CREATE_DESTRUCTIVE', 'wb'); // truncates existing file data, use with care
define('FOPEN_READ_WRITE_CREATE_DESTRUCTIVE', 'w+b'); // truncates existing file data, use with care
define('FOPEN_WRITE_CREATE', 'ab');
define('FOPEN_READ_WRITE_CREATE', 'a+b');
define('FOPEN_WRITE_CREATE_STRICT', 'xb');
define('FOPEN_READ_WRITE_CREATE_STRICT', 'x+b');
define('TBL_CATEGORIES', 'cibb_categories');
define('TBL_POSTS',      'cibb_posts');
define('TBL_THREADS',    'cibb_threads');
define('TBL_USERS',      'users');
define('TBL_ROLES',      'cibb_roles');
define('CIBB_TITLE',     ' &mdash; CIBB Forum');

/*
|--------------------------------------------------------------------------
| Display Debug backtrace
|--------------------------------------------------------------------------
|
| If set to TRUE, a backtrace will be displayed along with php errors. If
| error_reporting is disabled, the backtrace will not display, regardless
| of this setting
|
*/
define('SHOW_DEBUG_BACKTRACE', TRUE);

/*
|--------------------------------------------------------------------------
| Exit Status Codes
|--------------------------------------------------------------------------
|
| Used to indicate the conditions under which the script is exit()ing.
| While there is no universal standard for error codes, there are some
| broad conventions.  Three such conventions are mentioned below, for
| those who wish to make use of them.  The CodeIgniter defaults were
| chosen for the least overlap with these conventions, while still
| leaving room for others to be defined in future versions and user
| applications.
|
| The three main conventions used for determining exit status codes
| are as follows:
|
|    Standard C/C++ Library (stdlibc):
|       http://www.gnu.org/software/libc/manual/html_node/Exit-Status.html
|       (This link also contains other GNU-specific conventions)
|    BSD sysexits.h:
|       http://www.gsp.com/cgi-bin/man.cgi?section=3&topic=sysexits
|    Bash scripting:
|       http://tldp.org/LDP/abs/html/exitcodes.html
|
*/
define('EXIT_SUCCESS', 0); // no errors
define('EXIT_ERROR', 1); // generic error
define('EXIT_CONFIG', 3); // configuration error
define('EXIT_UNKNOWN_FILE', 4); // file not found
define('EXIT_UNKNOWN_CLASS', 5); // unknown class
define('EXIT_UNKNOWN_METHOD', 6); // unknown class member
define('EXIT_USER_INPUT', 7); // invalid user input
define('EXIT_DATABASE', 8); // database error
define('EXIT__AUTO_MIN', 9); // lowest automatically-assigned error code
define('EXIT__AUTO_MAX', 125); // highest automatically-assigned error code



define('STOPSHOPSTORELINK', "http://connectopiastore.com/stopshopstore"); // highest automatically-assigned error code
define('PORTALLINK', "http://connectopiastore.com/portal"); // highest automatically-assigned error code
$activity_log_types = array(
							"1" => 'Admin User',
							"2" => 'Packages',
							"3" => 'Users',
						);

$countries=array(
			'AF'=>'Afghanistan',
			'AL'=>'Albania',
			'DZ'=>'Algeria',
			'AS'=>'American Samoa',
			'AD'=>'Andorra',
			'AO'=>'Angola',
			'AI'=>'Anguilla',
			'AQ'=>'Antarctica',
			'AG'=>'Antigua and Barbuda',
			'AR'=>'Argentina',
			'AM'=>'Armenia',
			'AW'=>'Aruba',
			'AU'=>'Australia',
			'AT'=>'Austria',
			'AZ'=>'Azerbaijan',
			'BS'=>'Bahamas',
			'BH'=>'Bahrain',
			'BD'=>'Bangladesh',
			'BB'=>'Barbados',
			'BY'=>'Belarus',
			'BE'=>'Belgium',
			'BZ'=>'Belize',
			'BJ'=>'Benin',
			'BM'=>'Bermuda',
			'BT'=>'Bhutan',
			'BO'=>'Bolivia',
			'BA'=>'Bosnia and Herzegovina',
			'BW'=>'Botswana',
			'BV'=>'Bouvet Island',
			'BR'=>'Brazil',
			'IO'=>'British Indian Ocean Territory',
			'BN'=>'Brunei',
			'BG'=>'Bulgaria',
			'BF'=>'Burkina Faso',
			'BI'=>'Burundi',
			'KH'=>'Cambodia',
			'CM'=>'Cameroon',
			'CA'=>'Canada',
			'CV'=>'Cape Verde',
			'KY'=>'Cayman Islands',
			'CF'=>'Central African Republic',
			'TD'=>'Chad',
			'CL'=>'Chile',
			'CN'=>'China',
			'CX'=>'Christmas Island',
			'CC'=>'Cocos (Keeling) Islands',
			'CO'=>'Colombia',
			'KM'=>'Comoros',
			'CG'=>'Congo',
			'CD'=>'Congo (DRC)',
			'CK'=>'Cook Islands',
			'CR'=>'Costa Rica',
			'CI'=>'Côte d\'Ivoire',
			'HR'=>'Croatia',
			'CU'=>'Cuba',
			'CY'=>'Cyprus',
			'CZ'=>'Czech Republic',
			'DK'=>'Denmark',
			'DJ'=>'Djibouti',
			'DM'=>'Dominica',
			'DO'=>'Dominican Republic',
			'EC'=>'Ecuador',
			'EG'=>'Egypt',
			'SV'=>'El Salvador',
			'GQ'=>'Equatorial Guinea',
			'ER'=>'Eritrea',
			'EE'=>'Estonia',
			'ET'=>'Ethiopia',
			'FK'=>'Falkland Islands (Islas Malvinas)',
			'FO'=>'Faroe Islands',
			'FJ'=>'Fiji Islands',
			'FI'=>'Finland',
			'FR'=>'France',
			'GF'=>'French Guiana',
			'PF'=>'French Polynesia',
			'TF'=>'French Southern and Antarctic Lands',
			'GA'=>'Gabon',
			'GM'=>'Gambia, The',
			'GE'=>'Georgia',
			'DE'=>'Germany',
			'GH'=>'Ghana',
			'GI'=>'Gibraltar',
			'GR'=>'Greece',
			'GL'=>'Greenland',
			'GD'=>'Grenada',
			'GP'=>'Guadeloupe',
			'GU'=>'Guam',
			'GT'=>'Guatemala',
			'GG'=>'Guernsey',
			'GN'=>'Guinea',
			'GW'=>'Guinea-Bissau',
			'GY'=>'Guyana',
			'HT'=>'Haiti',
			'HM'=>'Heard Island and McDonald Islands',
			'HN'=>'Honduras',
			'HK'=>'Hong Kong SAR',
			'HU'=>'Hungary',
			'IS'=>'Iceland',
			'IN'=>'India',
			'ID'=>'Indonesia',
			'IR'=>'Iran',
			'IQ'=>'Iraq',
			'IE'=>'Ireland',
			'IM'=>'Isle of Man',
			'IL'=>'Israel',
			'IT'=>'Italy',
			'JM'=>'Jamaica',
			'JP'=>'Japan',
			'JE'=>'Jersey',
			'JO'=>'Jordan',
			'KZ'=>'Kazakhstan',
			'KE'=>'Kenya',
			'KI'=>'Kiribati',
			'KR'=>'Korea',
			'KW'=>'Kuwait',
			'KG'=>'Kyrgyzstan',
			'LA'=>'Laos',
			'LV'=>'Latvia',
			'LB'=>'Lebanon',
			'LS'=>'Lesotho',
			'LR'=>'Liberia',
			'LY'=>'Libya',
			'LI'=>'Liechtenstein',
			'LT'=>'Lithuania',
			'LU'=>'Luxembourg',
			'MO'=>'Macao SAR',
			'MK'=>'Macedonia, Former Yugoslav Republic of',
			'MG'=>'Madagascar',
			'MW'=>'Malawi',
			'MY'=>'Malaysia',
			'MV'=>'Maldives',
			'ML'=>'Mali',
			'MT'=>'Malta',
			'MH'=>'Marshall Islands',
			'MQ'=>'Martinique',
			'MR'=>'Mauritania',
			'MU'=>'Mauritius',
			'YT'=>'Mayotte',
			'MX'=>'Mexico',
			'FM'=>'Micronesia',
			'MD'=>'Moldova',
			'MC'=>'Monaco',
			'MN'=>'Mongolia',
			'ME'=>'Montenegro',
			'MS'=>'Montserrat',
			'MA'=>'Morocco',
			'MZ'=>'Mozambique',
			'MM'=>'Myanmar',
			'NA'=>'Namibia',
			'NR'=>'Nauru',
			'NP'=>'Nepal',
			'NL'=>'Netherlands',
			'AN'=>'Netherlands Antilles',
			'NC'=>'New Caledonia',
			'NZ'=>'New Zealand',
			'NI'=>'Nicaragua',
			'NE'=>'Niger',
			'NG'=>'Nigeria',
			'NU'=>'Niue',
			'NF'=>'Norfolk Island',
			'KP'=>'North Korea',
			'MP'=>'Northern Mariana Islands',
			'NO'=>'Norway',
			'OM'=>'Oman',
			'PK'=>'Pakistan',
			'PW'=>'Palau',
			'PS'=>'Palestinian Authority',
			'PA'=>'Panama',
			'PG'=>'Papua New Guinea',
			'PY'=>'Paraguay',
			'PE'=>'Peru',
			'PH'=>'Philippines',
			'PN'=>'Pitcairn Islands',
			'PL'=>'Poland',
			'PT'=>'Portugal',
			'PR'=>'Puerto Rico',
			'QA'=>'Qatar',
			'RE'=>'Reunion',
			'RO'=>'Romania',
			'RU'=>'Russia',
			'RW'=>'Rwanda',
			'WS'=>'Samoa',
			'SM'=>'San Marino',
			'ST'=>'São Tomé and Príncipe',
			'SA'=>'Saudi Arabia',
			'SN'=>'Senegal',
			'RS'=>'Serbia',
			'SC'=>'Seychelles',
			'SL'=>'Sierra Leone',
			'SG'=>'Singapore',
			'SK'=>'Slovakia',
			'SI'=>'Slovenia',
			'SB'=>'Solomon Islands',
			'SO'=>'Somalia',
			'ZA'=>'South Africa',
			'GS'=>'South Georgia and the South Sandwich Islands',
			'ES'=>'Spain',
			'LK'=>'Sri Lanka',
			'SH'=>'St. Helena',
			'KN'=>'St. Kitts and Nevis',
			'LC'=>'St. Lucia',
			'PM'=>'St. Pierre and Miquelon',
			'VC'=>'St. Vincent and the Grenadines',
			'SD'=>'Sudan',
			'SR'=>'Suriname',
			'SJ'=>'Svalbard and Jan Mayen',
			'SZ'=>'Swaziland',
			'SE'=>'Sweden',
			'CH'=>'Switzerland',
			'SY'=>'Syria',
			'TW'=>'Taiwan',
			'TJ'=>'Tajikistan',
			'TZ'=>'Tanzania',
			'TH'=>'Thailand',
			'TP'=>'Timor-Leste (East Timor)',
			'TG'=>'Togo',
			'TK'=>'Tokelau',
			'TO'=>'Tonga',
			'TT'=>'Trinidad and Tobago',
			'TN'=>'Tunisia',
			'TR'=>'Turkey',
			'TM'=>'Turkmenistan',
			'TC'=>'Turks and Caicos Islands',
			'TV'=>'Tuvalu',
			'UG'=>'Uganda',
			'UA'=>'Ukraine',
			'AE'=>'United Arab Emirates',
			'UK'=>'United Kingdom',
			'US'=>'United States',
			'UM'=>'United States Minor Outlying Islands',
			'UY'=>'Uruguay',
			'UZ'=>'Uzbekistan',
			'VU'=>'Vanuatu',
			'VA'=>'Vatican City',
			'VE'=>'Venezuela',
			'VN'=>'Vietnam',
			'VG'=>'Virgin Islands, British',
			'VI'=>'Virgin Islands, U.S.',
			'WF'=>'Wallis and Futuna',
			'YE'=>'Yemen',
			'ZM'=>'Zambia',
			'ZW'=>'Zimbabwe'
		);
define("COUNTRIES",serialize($countries));

$states = array(
			'AL'=>'Alabama',
			'AK'=>'Alaska',
			'AZ'=>'Arizona',
			'AR'=>'Arkansas',
			'CA'=>'California',
			'CO'=>'Colorado',
			'CT'=>'Connecticut',
			'DE'=>'Delaware',
			'DC'=>'District of Columbia',
			'FL'=>'Florida',
			'GA'=>'Georgia',
			'HI'=>'Hawaii',
			'ID'=>'Idaho',
			'IL'=>'Illinois',
			'IN'=>'Indiana',
			'IA'=>'Iowa',
			'KS'=>'Kansas',
			'KY'=>'Kentucky',
			'LA'=>'Louisiana',
			'ME'=>'Maine',
			'MD'=>'Maryland',
			'MA'=>'Massachusetts',
			'MI'=>'Michigan',
			'MN'=>'Minnesota',
			'MS'=>'Mississippi',
			'MO'=>'Missouri',
			'MT'=>'Montana',
			'NE'=>'Nebraska',
			'NV'=>'Nevada',
			'NH'=>'New Hampshire',
			'NJ'=>'New Jersey',
			'NM'=>'New Mexico',
			'NY'=>'New York',
			'NC'=>'North Carolina',
			'ND'=>'North Dakota',
			'OH'=>'Ohio',
			'OK'=>'Oklahoma',
			'OR'=>'Oregon',
			'PA'=>'Pennsylvania',
			'RI'=>'Rhode Island',
			'SC'=>'South Carolina',
			'SD'=>'South Dakota',
			'TN'=>'Tennessee',
			'TX'=>'Texas',
			'UT'=>'Utah',
			'VT'=>'Vermont',
			'VA'=>'Virginia',
			'WA'=>'Washington',
			'WV'=>'West Virginia',
			'WI'=>'Wisconsin',
			'WY'=>'Wyoming'
		);
define("STATES",serialize($states));
$phone_ext = array(
				"93 Afghanistan",
				"355 Albania",
				"213 Algeria",
				"684 American Samoa",
				"376 Andorra",
				"244 Angola",
				"809 Anguilla",
				"268 Antigua",
				"54 Argentina",
				"374 Armenia",
				"297 Aruba",
				"247 Ascension Island",
				"61 Australia",
				"672 Australian External Territories",
				"43 Austria",
				"994 Azerbaijan",
				"242 Bahamas",
				"246 Barbados",
				"973 Bahrain",
				"880 Bangladesh",
				"375 Belarus",
				"32 Belgium",
				"501 Belize",
				"229 Benin",
				"809 Bermuda",
				"975 Bhutan",
				"284 British Virgin Islands",
				"591 Bolivia",
				"387 Bosnia and Hercegovina",
				"267 Botswana",
				"55 Brazil",
				"284 British V.I.",
				"673 Brunei Darussalm",
				"359 Bulgaria",
				"226 Burkina Faso",
				"257 Burundi",
				"855 Cambodia",
				"237 Cameroon",
				"1 Canada",
				"238 CapeVerde Islands",
				"1 Caribbean Nations",
				"345 Cayman Islands",
				"238 Cape Verdi",
				"236 Central African Republic",
				"235 Chad",
				"56 Chile",
				"86 China (People's Republic)",
				"886 China-Taiwan",
				"57 Colombia",
				"269 Comoros and Mayotte",
				"242 Congo",
				"682 Cook Islands",
				"506 Costa Rica",
				"385 Croatia",
				"53 Cuba",
				"357 Cyprus",
				"420 Czech Republic",
				"45 Denmark",
				"246 Diego Garcia",
				"767 Dominca",
				"809 Dominican Republic",
				"253 Djibouti",
				"593 Ecuador",
				"20 Egypt",
				"503 El Salvador",
				"240 Equatorial Guinea",
				"291 Eritrea",
				"372 Estonia",
				"251 Ethiopia",
				"500 Falkland Islands",
				"298 Faroe (Faeroe) Islands (Denmark)",
				"679 Fiji",
				"358 Finland",
				"33 France",
				"596 French Antilles",
				"594 French Guiana",
				"241 Gabon (Gabonese Republic)",
				"220 Gambia",
				"995 Georgia",
				"49 Germany",
				"233 Ghana",
				"350 Gibraltar",
				"30 Greece",
				"299 Greenland",
				"473 Grenada/Carricou",
				"671 Guam",
				"502 Guatemala",
				"224 Guinea",
				"245 Guinea-Bissau",
				"592 Guyana",
				"509 Haiti",
				"504 Honduras",
				"852 Hong Kong",
				"36 Hungary",
				"354 Iceland",
				"91 India",
				"62 Indonesia",
				"98 Iran",
				"964 Iraq",
				"353 Ireland (Irish Republic; Eire)",
				"972 Israel",
				"39 Italy",
				"225 Ivory Coast (La Cote d'Ivoire)",
				"876 Jamaica",
				"81 Japan",
				"962 Jordan",
				"7 Kazakhstan",
				"254 Kenya",
				"855 Khmer Republic (Cambodia/Kampuchea)",
				"686 Kiribati Republic (Gilbert Islands)",
				"82 Korea, Republic of (South Korea)",
				"850 Korea, People's Republic of (North Korea)",
				"965 Kuwait",
				"996 Kyrgyz Republic",
				"371 Latvia",
				"856 Laos",
				"961 Lebanon",
				"266 Lesotho",
				"231 Liberia",
				"370 Lithuania",
				"218 Libya",
				"423 Liechtenstein",
				"352 Luxembourg",
				"853 Macao",
				"389 Macedonia",
				"261 Madagascar",
				"265 Malawi",
				"60 Malaysia",
				"960 Maldives",
				"223 Mali",
				"356 Malta",
				"692 Marshall Islands",
				"596 Martinique (French Antilles)",
				"222 Mauritania",
				"230 Mauritius",
				"269 Mayolte",
				"52 Mexico",
				"691 Micronesia (F.S. of Polynesia)",
				"373 Moldova",
				"33 Monaco",
				"976 Mongolia",
				"473 Montserrat",
				"212 Morocco",
				"258 Mozambique",
				"95 Myanmar (former Burma)",
				"264 Namibia (former South-West Africa)",
				"674 Nauru",
				"977 Nepal",
				"31 Netherlands",
				"599 Netherlands Antilles",
				"869 Nevis",
				"687 New Caledonia",
				"64 New Zealand",
				"505 Nicaragua",
				"227 Niger",
				"234 Nigeria",
				"683 Niue",
				"850 North Korea",
				"1 670 North Mariana Islands (Saipan)",
				"47 Norway",
				"968 Oman",
				"92 Pakistan",
				"680 Palau",
				"507 Panama",
				"675 Papua New Guinea",
				"595 Paraguay",
				"51 Peru",
				"63 Philippines",
				"48 Poland",
				"351 Portugal (includes Azores)",
				"1 787 Puerto Rico",
				"974 Qatar",
				"262 Reunion (France)",
				"40 Romania",
				"7 Russia",
				"250 Rwanda (Rwandese Republic)",
				"670 Saipan",
				"378 San Marino",
				"239 Sao Tome and Principe",
				"966 Saudi Arabia",
				"221 Senegal",
				"381 Serbia and Montenegro",
				"248 Seychelles",
				"232 Sierra Leone",
				"65 Singapore",
				"421 Slovakia",
				"386 Slovenia",
				"677 Solomon Islands",
				"252 Somalia",
				"27 South Africa",
				"34 Spain",
				"94 Sri Lanka",
				"290 St. Helena",
				"869 St. Kitts/Nevis",
				"508 St. Pierre &(et) Miquelon (France)",
				"249 Sudan",
				"597 Suriname",
				"268 Swaziland",
				"46 Sweden",
				"41 Switzerland",
				"963 Syrian Arab Republic (Syria)",
				"689 Tahiti (French Polynesia)",
				"886 Taiwan",
				"7 Tajikistan",
				"255 Tanzania (includes Zanzibar)",
				"66 Thailand",
				"228 Togo (Togolese Republic)",
				"690 Tokelau",
				"676 Tonga",
				"1 868 Trinidad and Tobago",
				"216 Tunisia",
				"90 Turkey",
				"993 Turkmenistan",
				"688 Tuvalu (Ellice Islands)",
				"256 Uganda",
				"380 Ukraine",
				"971 United Arab Emirates",
				"44 United Kingdom",
				"598 Uruguay",
				"1 USA",
				"7 Uzbekistan",
				"678 Vanuatu (New Hebrides)",
				"39 Vatican City",
				"58 Venezuela",
				"84 Viet Nam",
				"1 340 Virgin Islands",
				"681 Wallis and Futuna",
				"685 Western Samoa",
				"381 Yemen (People's Democratic Republic of)",
				"967 Yemen Arab Republic (North Yemen)",
				"381 Yugoslavia (discontinued)",
				"243 Zaire",
				"260 Zambia",
				"263 Zimbabwe"
			);
define("PHONE_EXT",serialize($phone_ext));