<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Zones extends CI_Controller {
	function __construct()
    {
        parent::__construct();
		$this->load->model('Zone_model');
		$this->load->library("pagination");
		$this->load->library('ion_auth');
		if (!$this->ion_auth->logged_in() && !$this->ion_auth->in_group(1)) {
			redirect(site_url('admin/'), 'refresh');
		}
    }
	public function index() {
		$data['page_title'] 	 = 'Zones';
		$data['page_heading']   = 'Zones';
		$data['zones'] = $this->Zone_model->getAll();
		//echo "<pre>"; print_r($data['zones']);exit;
		
        $parser['content']	   = $this->load->view('admin/zones/listing',$data,TRUE);
        $this->parser->parse('admin/template', $parser);
	}

	public function add_zones() {
		$data['page_title'] 	 = 'Add Zone';
		$data['page_heading']   = 'Add Zone';
		
		if ($this->input->post()) {
			$rules = array(
              	array(
                     'field'   => 'name',
                     'rules'   => 'required'
                ),
               	array(
                     'field'   => 'width',
                     'rules'   => 'required'
                )
            );

			$this->form_validation->set_rules($rules);
			if ($this->form_validation->run()) {
				$result = $this->Zone_model->addZone($this->input->post());
				if ($result) {
					$this->session->set_flashdata(
							'success',
							"Added Successfully"
					);
					redirect(base_url()."content");
				}
				else {
					$data['contentRow'] = $this->input->post();
				}
				redirect(site_url('admin/zones'), 'refresh');
			}
		}
        $parser['content'] = $this->load->view('admin/zones/add_zone',$data,TRUE);
        $this->parser->parse('admin/template', $parser);
	}

	public function linked_banners($id) {
		//echo $id;exit;
		$data['page_title'] 	 = 'Linked Banners';
		$data['page_heading']   = 'Linked Banners';

		$data['banners'] = $this->Zone_model->getAllbookings($id);
		$data['zone_id'] = $id;
		//echo "<pre>"; print_r($data['banners']);exit;
		$parser['content'] = $this->load->view('admin/zones/linked_banners',$data,TRUE);
        $this->parser->parse('admin/template', $parser);
	}

	public function link_banner($id) {
		$data['page_title'] 	 = 'Link Banner';
		$data['page_heading']   = 'Link Banner';
		$data['advertisers'] = $this->Zone_model->getAdvertisers();
		$data['zoneid'] = $id;
		//echo "<pre>"; print_r($data['advertisers']);exit;
		if ($this->input->post()) {
			//echo "<pre>"; print_r($_POST);exit;
			$data['banners'] = $this->Zone_model->getAdvertiserbanner($_POST['advertiser_id']);
			$data['zoneid'] = $_POST['zoneid'];
			//echo "<pre>"; print_r($data['banners']);exit;
			$all_banners = $this->load->view('admin/zones/advertiser_banners',$data);
			return $all_banners;
		}

		$parser['content'] = $this->load->view('admin/zones/link_banner',$data,TRUE);
        $this->parser->parse('admin/template', $parser);
	}
	public function save_booking() {
		//echo "<pre>"; print_r($_POST);exit;
		$t = time();
		$_POST['impressions_performed'] = 0;
		$_POST['clicks_performed'] = 0;
		$_POST['date_activated'] = $t;
		
		$result = $this->Zone_model->saveBooking($this->input->post());
		//echo $result;exit;
		if ($result) {
		
			$this->session->set_flashdata(
					'success',
					"Added Successfully"
			);
			redirect(base_url()."admin/zones");
		}
	}

	public function unlink_banner($id) {
		$result = $this->Zone_model->unlinkBanner($id);
		$this->session->set_flashdata(
					'success',
					"Banner Unlinked"
			);
			redirect(base_url()."admin/zones");
	}
	public function getcode($id) {
		// //echo $id;exit;
		$zoneid = $id;
		$js_path = "http://".$_SERVER['HTTP_HOST'].dirname($_SERVER['PHP_SELF'])."/jsServer.php";
		$click_path="http://".$_SERVER['HTTP_HOST'].dirname($_SERVER['PHP_SELF'])."/ck.php";
		$img_path="http://".$_SERVER['HTTP_HOST'].dirname($_SERVER['PHP_SELF'])."/ad.php";
		//$js_path = '';
		$output='
		<!-- ******************  The code below is generated by Ads Application    ****************** 
		* don\'t forget to replace RANDOM_NUMBERR_HERE with the code that generates a random number
		-->
		<script language="javascript"><!--//<![CDATA[
			var r=Math.floor((Math.random()*999999999));
			var params="?zoneid='.$zoneid.'&amp;referer="+escape(document.referrer)+"&amp;location="+escape(document.location)+"&amp;cb="+r;
			
			document.write("<script type=\'text/javascript\' src=\''.$js_path.'"+params+"\'>");
			document.write("<\/script>");
		//]]>--></script>
		<!-- ************** Ads code end *****************************  -->
		';
		?>
		<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
		<html xmlns="http://www.w3.org/1999/xhtml">
		<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Zone Code</title>
		</head>
		<body style="background-color:#FFF;">
		<form>
		<textarea rows="15" style="font-family:tahoma; font-size:12px; width:620px" name="ta"><?php echo $output; ?></textarea>
		<div align="center">
		<input type="button" value="Close" onclick="window.opener=null;window.close();">
		<input type="button" value="Select All" onclick="this.form.ta.focus();this.form.ta.select()">
		</div>
		</form>
		<br>
		</body>
		</html>
<?php 	}

}
?>